/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import javax.swing.ActionMap;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.modules.editor.NbEditorKit.NbGenerateGoToPopupAction;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.actions.GotoAction;
import org.netbeans.editor.ext.GotoDialogSupport;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//Window//OutlineWindow//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "OutlineWindowTopComponent",
        iconBase = "Window/outlineIcon.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "Window.OutlineWindowTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_OutlineWindowAction",
        preferredID = "OutlineWindowTopComponent"
)
@Messages({
    "CTL_OutlineWindowAction=OutlineWindow",
    "CTL_OutlineWindowTopComponent=OutlineWindow Window",
    "HINT_OutlineWindowTopComponent=This is a OutlineWindow window"
})






public final class OutlineWindowTopComponent extends TopComponent 
    implements ExplorerManager.Provider, Lookup.Provider {

    private ExplorerManager manager;
    
    public OutlineWindowTopComponent() {
        this.manager = new ExplorerManager();
        // TODO: Add actionmap here for adding new tree actions (go-to line)
        initComponents();
        setName(Bundle.CTL_OutlineWindowTopComponent());
        setToolTipText(Bundle.HINT_OutlineWindowTopComponent());
        ActionMap map = this.getActionMap();
        associateLookup (ExplorerUtils.createLookup (manager, map));
    }

    
    // switch all listeners on when component is shown
    protected void componentActivated() {
        ExplorerUtils.activateActions(manager, true);
    }
    // switch all listeners off when component is hidden
    protected void componentDeactivated() {
        ExplorerUtils.activateActions(manager, false);
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTree1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
